### ISSUE TITLE
The PID code doesn't handle a negative number correctly from the sensor

### ISSUE THREAD

**Issue by colinl** [colinl/Sonoff-Tasmota#2]
As reported by wienerdogracing [1] the PID code doesn't handle a negative number correctly from the sensor.

The code on line 187 in xdrv_92_pid.ino

if (value != NULL && strlen(value) > 0 && isdigit(value[0]) )

should be changed to

if (value != NULL && strlen(value) > 0 && isdigit(value[0]) || (value[0] == '-' && isdigit(value[1]) ) )

This checks to see if the first value of the sensor return is a digit and also check to see if the first value is a negative sign and the 2nd value is a digit.

[1] https://github.com/arendst/Sonoff-Tasmota/issues/2722

**Comment by colinl** [comment]
Actually I think that should be
if (value != NULL && strlen(value) > 0 && (isdigit(value[0]) || (value[0] == '-' && isdigit(value[1])) ) )

**Comment by ascillato** [comment]
Hi, @colinl, @wienerdogracing

This is a very nice add on for Tasmota. Great job!

So, for adding support for negative values and also load shutdown if the temperature sensor data is not correct, what do you think for the line 187 to be:

`if (value != NULL && strlen(value) > 0 && (isdigit(value[0]) || (value[0] == '-' && isdigit(value[1])) ) && strcmp(value,"0.0") ) {`

and to be added in line 201 and line 207:

`Timeprop_Set_Power( PID_USE_TIMPROP-1, 0 );`

Should be fine ?

**Comment by colinl** [comment]
@ascillato I am not sure what you are trying to achieve with the test for "0.0".  Zero is a perfectly valid result as the process value may be exactly that.
There is no need tao call Timeprop_Set_Power as the code already has a feature to select a failsafe value if the process value is not valid.  Set PID_MAX_INTERVAL to slightly longer than the maximum expected time between good samples and set PID_MANUAL_POWER to a safe power level (zero in your case). Remember that though your process may need zero power if there is, for example, a fault in the sensor, someone else's process may need full power in order to keep the process safe.

**Comment by ascillato** [comment]
Understood.

Thanks a lot for your feedback! :+1:
