### ISSUE TITLE
Doesn't compile with 6.2.9

### ISSUE THREAD

**Issue by SoundGuy** [colinl/Sonoff-Tasmota#4]
**Describe the bug**

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ X ] Searched the problem in issues and in the wiki
- [ X ] Hardware used : Sonoff Basic
- [X ] Provide the output of command ``status 0`` :

**To Reproduce**

i followed the insrtuctions. in my tasmota main platform io sonoff folder, put the time proportional file xdrv_91_timeprop.ini and for an error in line  125 
 ExecuteCommandPower(relayNos[i], newState);
i replaced it with 
ExecuteCommandPower(relayNos[i], newState,SRC_TIMER);

not sure if i should use that or SRC_IGNORE.

**Expected behavior**

**Screenshots**

**Additional context**

**(Please, remember to close the issue when the problem has been addressed)**

p.s .i'm not sure how to fork/merge/branch /pull request thing for things in github for open source projects or i would have fixed it myself.

**Comment by colinl** [comment]
Thanks for reporting this.  I haven't tried it with recent versions of Tasmota yet, I will have a look.

**Comment by colinl** [comment]
Thanks @SoundGuy your suggestion seems good, I have pushed the fix.  In fact I have used SRC_IGNORE as I think anything else could cause confusion, but it only affects what is shown in the log.
